# ZMK Studio 활성화 (필요한 경우)
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_USB=y

# 로터리 인코더 활성화 (사실)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 디스플레이 엔진 켜기
CONFIG_ZMK_DISPLAY=y
# 커스텀 화면 끄기 (혹시 남아있다면 명시적으로 차단)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n
# ZMK 순정 내장 화면 강제 활성화
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILTIN=y
