# ZMK Studio 활성화 (필요한 경우)
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_USB=y

# 로터리 인코더 활성화 (사실)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 디스플레이 엔진 켜기
CONFIG_ZMK_DISPLAY=y
# 사실: 디스플레이 작업이 키보드 입력을 가로막고 보드를 다운시키는 것을 방지해 (스레드 분리)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# 사실: LVGL 그래픽 엔진이 화면 버퍼를 그릴 때 메모리 부족으로 뻗는 것을 방지해 (16KB 강제 할당)
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_VDB_SIZE=100
